describe("Sign in 'Integrica' website,add writing off products operation, Examples", ()=>{
    const Sign_in_btn = ('.header__link')
    const Input_email = ('#login_email_input')
    const Input_password = ('#login_password_input')
    const Sign_in_end_btn = ('.btn')
    const Show_more_on_storage = (':nth-child(7) > [href="#"] > .m-menu__ver-arrow')
    const Operations_button = ('.m-menu__item--open > .m-menu__submenu > .m-menu__subnav > :nth-child(2) > .m-menu__link > .m-menu__link-text')
    const Click_on_operation_button = ('#client-actions')
    const Choice_operatoins  = ('.dropdown > .dropdown-menu > :nth-child(3)')
    const Choise_product_button = ('#product-operations-form > :nth-child(1) > .m-alert__text > .row > .col-12 > .select-item-wrapper > .multiselect > .multiselect__select')
    const Click_on_correct_product = ('Парфумована вода для жінок Lacoste Pour Femme 50 мл / RFH-819582')
    const Input_number_of_product = (':nth-child(3) > .input-group > .form-control')
    const Click_writing_off_button = ('.show > .modal-dialog > .modal-content > .modal-footer > .btn')
    it("All test", ()=>{
        cy.viewport(1720, 980)
        cy.visit('https://integrica.com.ua/')
        cy.get(Sign_in_btn).click()
        cy.get(Input_email).type(Cypress.env('usermail'))
        cy.get(Input_password).type(Cypress.env('password'))
        cy.get(Sign_in_end_btn).click()
        cy.get(Show_more_on_storage).click()
        cy.get(Operations_button).click()
        cy.get(Click_on_operation_button).click()
        cy.get(Choice_operatoins).click()
        cy.get(Choise_product_button).click()
        cy.contains(Click_on_correct_product).click()
        cy.get(Input_number_of_product).clear().type('20')
        cy.get(Click_writing_off_button).click()
    })
})