describe("Sign in 'Integrica' website,add client and add selling product operation, Examples", ()=>{
    const Sign_in_btn = ('.header__link')
    const Input_email = ('#login_email_input')
    const Input_password = ('#login_password_input')
    const Sign_in_end_btn = ('.btn')
    const Client_btn = ('.m-menu__nav > :nth-child(5) > .m-menu__link')
    const Add_client_btn = ('.no-data-wrapper > .btn')
    const Input_client_name = ('#client_name')
    const Input_client_surname = ('#client_last_name')
    const Input_client_phone  = ('#client_phone')
    const Source_of_engagement = (':nth-child(3) > .m-alert__text > .row > :nth-child(2) > .select-item-wrapper > .multiselect > .multiselect__select')
    const Choice_correct_source = ('Instagram')
    const Add_client_end_btn = ('.flex-row > .btn')
    const Show_more_on_storage = (':nth-child(7) > [href="#"] > .m-menu__ver-arrow')
    const Operations_button = ('.m-menu__item--open > .m-menu__submenu > .m-menu__subnav > :nth-child(2) > .m-menu__link > .m-menu__link-text')
    const Choice_operatoins  = ('//*[@id="client-actions"]')
    const Click_on_correct_operation = ('.dropdown > .dropdown-menu > :nth-child(2)')
    const Choise_product_button = ('#product-operations-form > :nth-child(1) > .m-alert__text > .row > .col-12 > .select-item-wrapper > .multiselect > .multiselect__select')
    const Click_on_correct_product = ('Парфумована вода для жінок Lacoste Pour Femme 50 мл / RFH-819582')
    const Sell_product_btn =('.show > .modal-dialog > .modal-content > .modal-footer > .btn')
    const Input_number_of_product = (':nth-child(3) > .input-group > .form-control')
    it("All test", ()=>{
        cy.viewport(1720, 980)
        cy.visit('https://integrica.com.ua/')
        cy.get(Sign_in_btn).click()
        cy.get(Input_email).type(Cypress.env('usermail'))
        cy.get(Input_password).type(Cypress.env('password'))
        cy.get(Sign_in_end_btn).click()
        cy.get(Client_btn).click()
        cy.get(Add_client_btn).click()
        cy.get(Input_client_name).type(Cypress.env('client_name'))
        cy.get(Input_client_surname).type(Cypress.env('client_surname'))
        cy.get(Input_client_phone).type(Cypress.env('client_phone'))
        cy.get(Source_of_engagement).click()
        cy.contains(Choice_correct_source).click()
        cy.get(Add_client_end_btn).click()
        cy.get(Show_more_on_storage).click()
        cy.get(Operations_button).click()
        cy.wait(2000)
        cy.xpath(Choice_operatoins).click()
        cy.get(Click_on_correct_operation).click()
        cy.get(Choise_product_button).click()
        cy.contains(Click_on_correct_product).should('be.visible').click()
        cy.get(Input_number_of_product).clear().type(Cypress.env('number_product'))
        cy.get(Sell_product_btn).click()
    })    
})
