describe("Sign in 'Integrica' website,add cash register with cash, Examples", ()=>{
    const Sign_in_btn = ('.header__link')
    const Input_email = ('#login_email_input')
    const Input_password = ('#login_password_input')
    const Sign_in_end_btn = ('.btn')
    const Cash_register_btn = (':nth-child(8) > .m-menu__link')
    const Add_cash_register_btn= ('.m-portlet__head-tools > div > .btn')
    const Input_title_of_cash_register = ('#account_title')
    const Input_balance_of_cash_register  = ('#account_start_balance')
    const Add_cash_register_end_btn = ('.modal-footer > .d-flex > .btn')
    const Add_income_to_another_cash_reg= ('.btn-outline-success')
    const Input_balance_of_second_cashreg = ('#income-sum')
    const Add_button = ('.show > .modal-dialog > .modal-content > .modal-footer > .btn')
    it("All test", ()=>{
        cy.viewport(1720, 980)
        cy.visit('https://integrica.com.ua/')
        cy.get(Sign_in_btn).click()
        cy.get(Input_email).type(Cypress.env('usermail'))
        cy.get(Input_password).type(Cypress.env('password'))
        cy.get(Sign_in_end_btn).click()
        cy.get(Cash_register_btn).click()
        cy.get(Add_cash_register_btn).click()
        cy.get(Input_title_of_cash_register).type(Cypress.env('title_cash_register'))
        cy.get(Input_balance_of_cash_register).clear().type(Cypress.env('balance_of_cash_register'))
        cy.get(Add_cash_register_end_btn).click()
        cy.get(Add_income_to_another_cash_reg).click()
        cy.get(Input_balance_of_second_cashreg).clear().type(Cypress.env('balance_of_secoend_cash_reg'))
        cy.get(Add_button).click()
    })
})