describe("Sign in and delete new advertisement", ()=>{
    const Input_user_phone = ('.login-page > .login-box > .login-tabs > .login-tabs__content > .active > .login-form > #loginForm > .standard-login-box > :nth-child(2) > .focusbox > #userEmail')
    const Input_user_password = ('.login-page > .login-box > .login-tabs > .login-tabs__content > .active > .login-form > #loginForm > .standard-login-box > :nth-child(3) > .focusbox > [data-cy="login_input_password"]')
    const Click_sign_in_button = ('.login-page > .login-box > .login-tabs > .login-tabs__content > .active > .login-form > #loginForm > .standard-login-box > #se_userLogin')
    const Click_on_close_alert_btn = ('button[class="css-spwpto"]')
    const Click_on_olx_logo = ('.css-1kpgv52')
    const Click_on_my_profile_btn = ('#topLoginLink')
    const Click_on_unpaid_advertisement = ('Неоплачені')
    const Click_deactivation_btn = (':nth-child(1) > .css-1vr8bhw > .css-11fg3pa > .css-1tlwyxe > .css-7gl518 > [data-testid="inventory-item-actions"] > :nth-child(3) > .css-2124bz-BaseStyles')

    it("Sign in", ()=>{
        cy.visit("https://www.olx.ua/uk/account/?ref%5B0%5D%5Baction%5D=myaccount&ref%5B0%5D%5Bmethod%5D=index")
        cy.viewport(1720, 980)
        cy.get(Input_user_phone).type("0687664945")
        cy.get(Input_user_password).type("Luhude69")
        cy.get(Click_sign_in_button).click() 
        cy.wait(8000)
        cy.get(Click_on_close_alert_btn).click()
        cy.get(Click_on_olx_logo).click()
        cy.get(Click_on_my_profile_btn).click()
        cy.contains(Click_on_unpaid_advertisement).click()
        cy.get(Click_deactivation_btn).click()
        cy.wait(6000)
        cy.contains('Надаємо послуги прибиральниць').should('to.not.equal')
    })
}) 
  