describe("Sign in 'Integrica' website and add record on servicefor two clients, Examples", ()=>{
    const Sign_in_btn = ('.header__link')
    const Input_email = ('#login_email_input')
    const Input_password = ('#login_password_input')
    const Sign_in_end_btn = ('.btn')
    const Calendar_button = ('.m-menu__nav > :nth-child(4) > .m-menu__link')
    const Add_record_btn = ('.btn-md')
    const Choice_client_for_service = ('.form-group > .row > .col > .select-item-wrapper > .multiselect > .multiselect__select')
    const Choice_correct_client = ('Ольга Козацька')
    const Choice_service_btn  = ('.form-group > .row > .col-12 > .select-item-wrapper > .multiselect > .multiselect__select')
    const Choice_correct_service = ('Лазерна депіляція')
    const Choice_data_for_service = ('[data-day="26.11.2022"]')
    const Add_button = ('.justify-content-between > .d-flex > .btn')
    const Add_record_second_btn = ('.btn-md')
    const Choice_second_client_for_service = ('.form-group > .row > .col > .select-item-wrapper > .multiselect > .multiselect__select')
    const Choice_second_correct_client = ('Володимир Козацький')
    const Choice_other_service_btn  = ('.form-group > .row > .col-12 > .select-item-wrapper > .multiselect > .multiselect__select')
    const Choice_other_correct_service = ('Видалення родимок')
    const Choice_data_for_second_service = ('[data-day="27.11.2022"]')
    const Add_button_again = ('.justify-content-between > .d-flex > .btn')
    it("All test", ()=>{
        cy.viewport(1720, 980)
        cy.visit('https://integrica.com.ua/')
        cy.get(Sign_in_btn).click()
        cy.get(Input_email).type(Cypress.env('usermail'))
        cy.get(Input_password).type(Cypress.env('password'))
        cy.get(Sign_in_end_btn).click()
        cy.get(Calendar_button).click()
        cy.get(Add_record_btn).click()
        cy.get(Choice_client_for_service).click()
        cy.contains(Choice_correct_client).click()
        cy.get(Choice_service_btn).click()
        cy.contains(Choice_correct_service).click()
        cy.get(Choice_data_for_service).click()
        cy.get(Add_button).click()
        cy.get(Add_record_second_btn).click()
        cy.get(Choice_second_client_for_service).click()
        cy.contains(Choice_second_correct_client).click()
        cy.get(Choice_other_service_btn).click()
        cy.contains(Choice_other_correct_service).click()
        cy.get(Choice_data_for_second_service).click()
        cy.get(Add_button_again).click()
    })
})