describe("Sign in account and change contact detials", ()=>{
    const Input_user_phone = ('.login-page > .login-box > .login-tabs > .login-tabs__content > .active > .login-form > #loginForm > .standard-login-box > :nth-child(2) > .focusbox > #userEmail')
    const Input_user_password = ('.login-page > .login-box > .login-tabs > .login-tabs__content > .active > .login-form > #loginForm > .standard-login-box > :nth-child(3) > .focusbox > [data-cy="login_input_password"]')
    const Click_sign_in_button = ('.login-page > .login-box > .login-tabs > .login-tabs__content > .active > .login-form > #loginForm > .standard-login-box > #se_userLogin')
    const Click_on_close_alert_btn = ('button[class="css-spwpto"]')
    const Click_on_olx_logo = ('.css-1kpgv52')
    const Click_showe_more = ('#topLoginLink')
    const Click_on_settings_btn = ('#login-box-settings')
    const Click_on_cotnact_detials = ('.content > :nth-child(1)')
    const Input_city = ('#geoCity')
    const Input_name = ('#defaultPerson')
    const Save_button = ('#submitDefault')
    const Click_on_name_city = (':nth-child(2) > .pdingleft20')
    

    it("Sign in account and buying item", ()=>{
        cy.visit("https://www.olx.ua/uk/account/?ref%5B0%5D%5Baction%5D=myaccount&ref%5B0%5D%5Bmethod%5D=index")
        cy.viewport(1720, 980)
        cy.get(Input_user_phone).type("0687664945{home}")
        cy.get(Input_user_password).type("Luhude69")
        cy.get(Click_sign_in_button).click()
        cy.wait(8000)
        cy.get(Click_on_close_alert_btn).click()
        cy.get(Click_on_olx_logo).click()
        cy.get(Click_showe_more).trigger('mouseover')
        cy.get(Click_on_settings_btn).click()
        cy.get(Click_on_cotnact_detials).click()
        cy.get(Input_city).clear().type('Львів,Львівська область,Галицький{home}')
        cy.get(Input_name).clear().type('Олександр{enter}')
        cy.get(Save_button).click()
    })
})